


export const LIST_ALL_TWEETS = "LIST_ALL_TWEETS"
export const LIST_ALL_TWEETS_FAILURE = "LIST_ALL_TWEETS_FAILURE"
export const ADD_THE_TWEET = "ADD_THE_TWEET"
export const ADD_THE_TWEET_FAILURE = "ADD_THE_TWEET-FAILURE"

