

export const LIST_ALL_USERS = "LIST_ALL_USERS"
export const LIST_ALL_USERS_FAILURE = "LIST_ALL_USERS_FAILURE"
export const USER_DETAILS = "USER_DETAILS"
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE"
export const USER_REGISTRATION = "USER_REGISTRATION"
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE"
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"
export const DELETE_USER = "DELETE_USER"
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE"
