

export const LIST_ALL_USERS = "LIST_ALL_USERS"
export const LIST_ALL_USERS_FAILURE = "LIST_ALL_USERS_FAILURE"
export const USER_DETAILS = "USER_DETAILS"
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE"
