//List of action types/"scenarios" while performing CRUD ops against the COMMENTS API endpoints


export const GET_COMMENT = "GET_COMMENTS"
export const GET_COMMENT_FAILED = "GET_COMMENTS_FAILED"
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS"
export const GET_ALL_COMMENTS_FAILED = "GET_ALL_COMMENTS_FAILED"
export const UPDATE_COMMENT = "UPDATED_COMMENT"
export const UPDATE_COMMENT_FAILED = "UPDATE_COMMENT_FAILED"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENT_FAILED"