//List of action types/"scenarios" while performing CRUD ops against the COMMENTS API endpoints

export const REGISTER_COMMENTS = "REGISTER_COMMENTS";
export const REGISTER_COMMENTS_FAILED = "REGISTER_COMMENTS_FAILED"
export const GET_COMMENTS = "GET_COMMENTS"
export const GET_COMMENTS_FAILED = "GET_COMMENTS_FAILED"
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS"
export const GET_ALL_COMMENTS_FAILED = "GET_ALL_COMMENTS_FAILED"
export const UPDATE_COMMENTS = "UPDATED_COMMENTS"
export const UPDATE_COMMENTS_FAILED = "UPDATE_COMMENTS_FAILED"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const DELETE_COMMENTS = "DELETE_COMMENTS"
export const DELETE_COMMENTS_FAILED = "DELETE_COMMENTS_FAILED"