//List of action types/"scenarios" while performing CRUD ops against the COMMENTS API endpoints


export const GET_COMMENT = "GET_COMMENTS"
export const GET_COMMENT_FAILED = "GET_COMMENTS_FAILED"
export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS"
export const GET_ALL_COMMENTS_FAILED = "GET_ALL_COMMENTS_FAILED"
export const UPDATE_COMMENTS = "UPDATED_COMMENTS"
export const UPDATE_COMMENTS_FAILED = "UPDATE_COMMENTS_FAILED"
export const DELETE_COMMENT = "DELETE_COMMENTS"
export const DELETE_COMMENT_FAILED = "DELETE_COMMENTS_FAILED"